
entryPoints:
  web:
    address: ":80"

  web-secure:
    address: ":443"

  meteor:
    address: ":3000"

  expo0:
    address: ":19000"

  expo1:
    address: ":19001"

  expo2:
    address: ":19002"

  expo6:
    address: ":19006"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"

certificatesResolvers:
  myresolver:
    acme:
      email: info@domain.com
      storage: /acme.json
      httpChallenge:
        entryPoint: web
